config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :doses, only: [:destroy]

  resources :cocktails do
    resources :doses
  end

  # resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  before_destroy :check_for_cocktails

  validates :name, uniqueness: true, presence: true

  def self.list_names
    pluck(:name).sort
  end

  private

  def check_for_cocktails
    if doses.any?
      'Cannot Delete Ingredient while Cocktail exist'
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

   before_action :set_cocktail, only: [:show, :destroy, :edit]
  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new (cocktail_params)
    @cocktail.save

    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  def index
    @doses = Dose.all
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/delete.html.erb
<h1>Cocktails#delete</h1>
<p>Find me in app/views/cocktails/delete.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>please fill in the form</p>
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :name %>
  <%= f.submit "Submit Edits", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('../../assets/cocktail_banner.png');">
  <div class="banner-content">
    <div id="header">
    <h1>Le Wagon Cocktails</h1>
    <p>Experience the art of mixing</p>
    <%= link_to "Add a new cocktail", new_cocktail_path, class: "btn btn-primary" %>
    </div>
  <div class="container">
  <div class="row">
    <% @cocktails.each do |c| %>
    <div class="col-xs-12 col-sm-4">

      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= c.photo %>');">
        <div class="card-description">
         <h2> <%= c.name %> </h2>
         <p>
          <%= link_to "Edit", edit_cocktail_path(c) %>
          <%= link_to "Add a Dose", new_cocktail_dose_path(c) %>
          <%= link_to "Delete", c, method: :delete, data: { confirm: "Are you sure?" } %>
         </p>
       </div>

        <div class="card-details"> <%= link_to "Show Details", cocktail_path(c) %> </div>
        <!-- <a class="card-link" href="<%= cocktail_path(c) %>" ></a> -->
      </div>

    </div>
    <% end %>

    </div>
  </div>
</div>

  </div>
</div>


<!-- <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%=@cocktails.first.photo%>');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <a class="card-link" href="#" ></a>
</div> -->

app/views/cocktails/new.html.erb
<h1>Add a new cocktail</h1>
<p>please fill in the form</p>
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :name %>
  <%= f.submit "add a cocktail name", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<h1>Cocktail Page</h1>
<h2> <%= @cocktail.name %> </h2>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
<div class="cocktail-header">
  <div class="cocktail-menu">
    <div id="cocktail-ingredients">
      <% @cocktail.doses.each do |dose| %>
        <div class="ingredient">
          <%= dose.ingredient.name%>
          <span><%= dose.description %></span>
          <span>
            <%= link_to "Delete Dose", dose_path(dose), method: :delete, data: {confirm: "Are you sure?"} %>
          </span>
        </div>
      <% end %>
    </div>
    <%= link_to "Add a Dose", new_cocktail_dose_path(@cocktail) %>
  </div>
</div>


<%= link_to "Cocktails", cocktails_path %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<div class="container">
  <h1>Add Doses to <%= @cocktail.name %></h1>
  <div class="row">
    <div class="col-sm-6">
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.association :ingredient %>
          <%= f.input :description %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>